name: when2heat
channels:
  - defaults
  - conda-forge
dependencies:
  - geopandas=0.9
  - jupyter=1.0
  - netcdf4=1.5
  - pandas=1.3
  - pip
  - python=3.7
  - pyyaml
  - pip:
    - openpyxl
    - cdsapi==0.5.1

